### ISSUE TITLE
Appears that the code still looks for adversarial_method rather than method argument. AttributeError: 'Namespace' object has no attribute 'adversarial_method'   

### ISSUE THREAD

**Issue by rounakskm** [joshr17/IFM#2]
Hello,
Cloned master and tried to run the code. Encountered this minor error.

Can be easily fixed by changing adversarial_method in line 170 and 175 to method

Here is the error trace:

`Use GPU: 0 for training
Traceback (most recent call last):
  File "main_moco.py", line 432, in <module>
    main()
  File "main_moco.py", line 141, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/opt/anaconda3/envs/torch_env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/anaconda3/envs/torch_env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/opt/anaconda3/envs/torch_env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 4 terminated with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/torch_env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/soumya/IFM/moco-master/main_moco.py", line 170, in main_worker
    if args.adversarial_method is None:
AttributeError: 'Namespace' object has no attribute 'adversarial_method'`

Feel free to close the issue

**Comment by rounakskm** [comment]
``

**Comment by rounakskm** [comment]
Reopening as I do not know if I should close this issue

**Comment by nzw0301** [comment]
As you said, I suppose that replacing `args.adversarial_method` with `args.method` might resolve the issue.
